# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 500)
        MainWindow.setMinimumSize(QtCore.QSize(850, 500))
        MainWindow.setMaximumSize(QtCore.QSize(850, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 10, 391, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_stock_num = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_stock_num.setObjectName("lineEdit_stock_num")
        self.gridLayout.addWidget(self.lineEdit_stock_num, 0, 1, 1, 1)
        self.label_stock_num = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_stock_num.setObjectName("label_stock_num")
        self.gridLayout.addWidget(self.label_stock_num, 0, 0, 1, 1)
        self.pushButton_send = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_send.setObjectName("pushButton_send")
        self.gridLayout.addWidget(self.pushButton_send, 0, 2, 1, 1)
        self.tabledata = QtWidgets.QTableWidget(self.centralwidget)
        self.tabledata.setGeometry(QtCore.QRect(30, 60, 811, 201))
        self.tabledata.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabledata.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabledata.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tabledata.setShowGrid(True)
        self.tabledata.setGridStyle(QtCore.Qt.SolidLine)
        self.tabledata.setObjectName("tabledata")
        self.tabledata.setColumnCount(8)
        self.tabledata.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tabledata.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabledata.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabledata.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabledata.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabledata.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabledata.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabledata.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabledata.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabledata.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabledata.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabledata.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabledata.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabledata.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabledata.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabledata.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabledata.setItem(5, 0, item)
        self.tabledata.horizontalHeader().setCascadingSectionResizes(False)
        self.tableprice = QtWidgets.QTableWidget(self.centralwidget)
        self.tableprice.setGeometry(QtCore.QRect(30, 340, 741, 111))
        self.tableprice.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableprice.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableprice.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableprice.setShowGrid(True)
        self.tableprice.setGridStyle(QtCore.Qt.SolidLine)
        self.tableprice.setObjectName("tableprice")
        self.tableprice.setColumnCount(7)
        self.tableprice.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableprice.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableprice.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableprice.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableprice.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableprice.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableprice.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableprice.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableprice.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableprice.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableprice.setHorizontalHeaderItem(6, item)
        self.tableprice.horizontalHeader().setCascadingSectionResizes(False)
        self.label_ps1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ps1.setGeometry(QtCore.QRect(30, 470, 681, 20))
        self.label_ps1.setObjectName("label_ps1")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 290, 391, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_eps = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_eps.setObjectName("lineEdit_eps")
        self.gridLayout_2.addWidget(self.lineEdit_eps, 0, 1, 1, 1)
        self.label_eps = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_eps.setObjectName("label_eps")
        self.gridLayout_2.addWidget(self.label_eps, 0, 0, 1, 1)
        self.pushButton_calc = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_calc.setObjectName("pushButton_calc")
        self.gridLayout_2.addWidget(self.pushButton_calc, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_stock_num.setText(_translate("MainWindow", "股票代號"))
        self.pushButton_send.setText(_translate("MainWindow", "送出"))
        self.tabledata.setSortingEnabled(True)
        item = self.tabledata.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "年度"))
        item = self.tabledata.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "最高股價"))
        item = self.tabledata.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "最低股價"))
        item = self.tabledata.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "平均股價"))
        item = self.tabledata.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "EPS"))
        item = self.tabledata.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "最高本益比"))
        item = self.tabledata.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "最低本益比"))
        item = self.tabledata.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "平均本益比"))
        __sortingEnabled = self.tabledata.isSortingEnabled()
        self.tabledata.setSortingEnabled(False)
        item = self.tabledata.item(5, 0)
        item.setText(_translate("MainWindow", "平均"))
        self.tabledata.setSortingEnabled(__sortingEnabled)
        self.tableprice.setSortingEnabled(True)
        item = self.tableprice.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "便宜價"))
        item = self.tableprice.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "合理價"))
        item = self.tableprice.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "昂貴價"))
        item = self.tableprice.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "0%"))
        item = self.tableprice.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "5%"))
        item = self.tableprice.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "10%"))
        item = self.tableprice.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "15%"))
        item = self.tableprice.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "20%"))
        item = self.tableprice.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "25%"))
        item = self.tableprice.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "30%"))
        self.label_ps1.setText(_translate("MainWindow", "附註: 「預估EPS」必須要由我們提供，來源有二，第一是先找法人預估值，第二則是抓公司最近4季的EPS，再相加成一年。"))
        self.label_eps.setText(_translate("MainWindow", "預估EPS:"))
        self.pushButton_calc.setText(_translate("MainWindow", "計算"))

